### PR TITLE
Update .gitpod.yml

### PR DESCRIPTION
**Pull request by Soecka**
- Use Node 12
- Fix Invalid Host Header

### CODE REVIEW

**Comment by Soecka** [comment]
Sorry for the noise commit, I simply tested if the .gitpod.yml works. Only the .gitpod.yml had been updated

**Comment by 64json** [comment]
https://www.gitpod.io/docs/languages/javascript#node-versions

It seems like the official Gitpod docs recommend to create a `.gitpod.Dockerfile` for this purpose. Not very sure but might have better caching, etc. this way.

**Comment by Soecka** [comment]
> https://www.gitpod.io/docs/languages/javascript#node-versions
> 
> It seems like the official Gitpod docs recommend to create a `.gitpod.Dockerfile` for this purpose. Not very sure but might have better caching, etc. this way.

I follow the instructions of official docs, it spent 50 second to prepare the image, but turn out to be fine with the node version

**Comment by lxzzz** [comment]
[自动回复]您的邮件已收到，会尽快给您答复。

**Comment by bookerdong** [comment]
你的邮件已收到

**Review by skydiver1980 — APPROVED** [review]

**Comment by bookerdong** [comment]
你的邮件已收到

**Comment by lxzzz** [comment]
[自动回复]您的邮件已收到，会尽快给您答复。

**Pull request closed without merging**
